package creditcard.views;

import creditcard.models.Copper;
import creditcard.models.CreditCardType;
import creditcard.models.Gold;
import creditcard.models.Silver;
import framework.views.FinCoView;

import javax.swing.*;
import java.awt.*;


public class JDialog_AddCompAcc extends JDialog {
	private ICCardViewController controller;
	private FinCoView parent;

	JRadioButton copperRB = new JRadioButton();
	JRadioButton goldRB = new JRadioButton();
	JRadioButton silverRB = new JRadioButton();

	JLabel nameLb = new JLabel();
	JLabel streetLb = new JLabel();
	JLabel cityLb = new JLabel();
	JLabel stateLb = new JLabel();
	JLabel zipLb = new JLabel();
	JLabel noEmployeesLb = new JLabel();
	JLabel emailLb = new JLabel();
	JLabel ccNumberLb = new JLabel();
	JLabel expiryDateLb = new JLabel();

	JTextField nameTF = new JTextField();
	JTextField cityTF = new JTextField();
	JTextField stateTF = new JTextField();
	JTextField streetTF = new JTextField();
	JTextField zipTF = new JTextField();
	JTextField noEmployeesTF = new JTextField();
	JTextField emailTF = new JTextField();
	JTextField ccNumberTF = new JTextField();
	JTextField expiryDateTF = new JTextField();

	JButton okayBt = new JButton();
	JButton cancelBt = new JButton();

	public JDialog_AddCompAcc(FinCoView parent, ICCardViewController controller) {
		super(parent);

		this.controller = controller;
		this.parent = parent;
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parses your Java file into its visual environment. 
		//{{ INIT_CONTROLS 
		setTitle("Add company credit card account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(301,373);
		setVisible(false);

		goldRB.setText("Gold");
		goldRB.setActionCommand("Gold");
		getContentPane().add(goldRB);
		goldRB.setBounds(36,12,84,24);

		silverRB.setText("Silver");
		silverRB.setActionCommand("Silver");
		getContentPane().add(silverRB);
		silverRB.setBounds(36,36,84,24);

		copperRB.setText("Copper");
		copperRB.setActionCommand("Copper");
		getContentPane().add(copperRB);
		copperRB.setBounds(36,60,84,24);


		nameLb.setText("Name");
		getContentPane().add(nameLb);
		nameLb.setForeground(Color.black);
		nameLb.setBounds(12,108,48,24);
		
		streetLb.setText("Street");
		getContentPane().add(streetLb);
		streetLb.setForeground(Color.black);
		streetLb.setBounds(12,132,48,24);
		
		cityLb.setText("City");
		getContentPane().add(cityLb);
		cityLb.setForeground(Color.black);
		cityLb.setBounds(12,156,48,24);
		
		stateLb.setText("State");
		getContentPane().add(stateLb);
		stateLb.setForeground(Color.black);
		stateLb.setBounds(12,180,48,24);
		
		zipLb.setText("Zip");
		getContentPane().add(zipLb);
		zipLb.setForeground(Color.black);
		zipLb.setBounds(12,204,48,24);

		emailLb.setText("Email");
		getContentPane().add(emailLb);
		emailLb.setForeground(Color.black);
		emailLb.setBounds(12,228,48,24);

		ccNumberLb.setText("CC number");
		getContentPane().add(ccNumberLb);
		ccNumberLb.setForeground(Color.black);
		ccNumberLb.setBounds(12,252,96,24);

		expiryDateLb.setText("Exp. Date");
		getContentPane().add(expiryDateLb);
		expiryDateLb.setForeground(Color.black);
		expiryDateLb.setBounds(12,276,72,24);

		noEmployeesLb.setText("No of employees");
		getContentPane().add(noEmployeesLb);
		noEmployeesLb.setForeground(Color.black);
		noEmployeesLb.setBounds(12,300,96,24);

		
		getContentPane().add(nameTF);
		nameTF.setBounds(120,108,156,20);
		
		getContentPane().add(streetTF);
		streetTF.setBounds(120,132,156,20);
		
		getContentPane().add(cityTF);
		cityTF.setBounds(120,156,156,20);
		
		getContentPane().add(stateTF);
		stateTF.setBounds(120,180,156,20);
		
		getContentPane().add(zipTF);
		zipTF.setBounds(120,204,156,20);

		getContentPane().add(emailTF);
		emailTF.setBounds(120,228,156,20);

		getContentPane().add(ccNumberTF);
		ccNumberTF.setBounds(120,252,156,20);

		getContentPane().add(expiryDateTF);
		expiryDateTF.setBounds(120,276,156,20);

		getContentPane().add(noEmployeesTF);
		noEmployeesTF.setBounds(120,300,156,20);

		
		okayBt.setText("OK");
		okayBt.setActionCommand("OK");
		getContentPane().add(okayBt);
		okayBt.setBounds(48,336,84,24);
		
		cancelBt.setText("Cancel");
		cancelBt.setActionCommand("Cancel");
		getContentPane().add(cancelBt);
		cancelBt.setBounds(156,336,84,24);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		okayBt.addActionListener(lSymAction);
		cancelBt.addActionListener(lSymAction);
		//}}
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == okayBt)
				JButtonOK_actionPerformed(event);
			else if (object == cancelBt)
				JButtonCalcel_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {

		String clientName = nameTF.getText().trim();
		String street = streetTF.getText().trim();
		String city = cityTF.getText().trim();
		int zip;
		try {
			zip = Integer.parseInt(zipTF.getText().trim());
		} catch (NumberFormatException e) {
			e.printStackTrace();
			zip = 0;
		}
		String state = stateTF.getText().trim();
		String ccNumber = ccNumberTF.getText().trim();
		String expiryDate = expiryDateTF.getText().trim();
		String email = emailTF.getText().trim();
		String noOfEmployees = noEmployeesTF.getText().trim();

		CreditCardType cardType;

		if (goldRB.isSelected())
			cardType = new Gold();
		else if (silverRB.isSelected())
			cardType = new Silver();
		else
			cardType = new Copper();

		this.controller.createCompanyAccount(ccNumber, clientName, street, city, state, zip, email, noOfEmployees, expiryDate, cardType);
		this.parent.newaccount = true;

		dispose();

	}

	void JButtonCalcel_actionPerformed(java.awt.event.ActionEvent event)
	{
		dispose();
			 
	}
}
